### ISSUE TITLE
Facebook --> Meta naming

### ISSUE THREAD

**Issue by bmcase** [facebookresearch/fbpcf#415]
We should update the naming from "Facebook Private Computation Framework" to "Meta Private Computation Framework" and all the places in the documentation where we use that.

**Comment by robotal** [comment]
@bmcase Are you proposing to change the github url as well as naming in code to MPCF? As far as I know, we're not able to rename an existing github repository, so this would require creating a fork of this repository called MPCF. This would also have implications to our Build and Release which is a high level of investment for us.

Theoretically we can update the documentation to call it Meta Private Computation Framework, but this would be inconsistent with the repository name itself. I think we also have some publications out already that talk about "fbpcf". It would most likely require a centralized effort from all of PC.

**Comment by robotal** [comment]
We've updated the documentation to highlight that the framework is called "PCF". Closing out this issue.

**Comment by bmcase** [comment]
@robotal ,  sounds good.
